#ifndef YIS_RUNTIME_EMBEDDED_H
#define YIS_RUNTIME_EMBEDDED_H

// Auto-generated snapshot of yis/src/runtime.inc with // @include expansion.
// Used as a fallback when runtime.inc is not available next to the yis binary.
// Regenerate with: yis/tools/gen_runtime_embedded.sh

static const char yis_runtime_embedded[] =
"// ---- Yis runtime (minimal) ----\n"
"#include <stdio.h>\n"
"#include <stdlib.h>\n"
"#include <string.h>\n"
"#include <stdbool.h>\n"
"#include <stdint.h>\n"
"#include <stdarg.h>\n"
"#include <ctype.h>\n"
"#include <math.h>\n"
"#include <limits.h>\n"
"#include <time.h>\n"
"#include <sys/stat.h>\n"
"#include <stddef.h>\n"
"#include <errno.h>\n"
"#if defined(__APPLE__)\n"
"#include <CoreGraphics/CoreGraphics.h>\n"
"#endif\n"
"\n"
"#if defined(_WIN32)\n"
"#include <windows.h>\n"
"#include <io.h>\n"
"#include <direct.h>\n"
"#endif\n"
"#if !defined(_WIN32)\n"
"#include <dirent.h>\n"
"#endif\n"
"#include <unistd.h>\n"
"\n"
"static int yis_stdout_isatty = 0;\n"
"\n"
"static int yis_argc = 0;\n"
"static char **yis_argv = NULL;\n"
"\n"
"void yis_set_args(int argc, char **argv) {\n"
"  yis_argc = argc;\n"
"  yis_argv = argv;\n"
"}\n"
"\n"
"static void yis_runtime_init(void) {\n"
"#if defined(_WIN32)\n"
"  yis_stdout_isatty = _isatty(_fileno(stdout));\n"
"#else\n"
"  yis_stdout_isatty = isatty(fileno(stdout));\n"
"#endif\n"
"  if (!yis_stdout_isatty) {\n"
"    setvbuf(stdout, NULL, _IOFBF, 1 << 16);\n"
"  }\n"
"}\n"
"\n"
"typedef enum {\n"
"  EVT_NULL,\n"
"  EVT_INT,\n"
"  EVT_FLOAT,\n"
"  EVT_BOOL,\n"
"  EVT_STR,\n"
"  EVT_ARR,\n"
"  EVT_DICT,\n"
"  EVT_OBJ,\n"
"  EVT_FN\n"
"} YisTag;\n"
"\n"
"typedef struct YisVal YisVal;\n"
"\n"
"typedef struct YisStr {\n"
"  int ref;\n"
"  size_t len;\n"
"  char* data;\n"
"} YisStr;\n"
"\n"
"typedef struct YisArr {\n"
"  int ref;\n"
"  size_t len;\n"
"  size_t cap;\n"
"  YisVal* items;\n"
"} YisArr;\n"
"\n"
"struct YisVal {\n"
"  YisTag tag;\n"
"  union {\n"
"    int64_t i;\n"
"    double f;\n"
"    bool b;\n"
"    void* p;\n"
"  } as;\n"
"};\n"
"\n"
"typedef struct YisDictEnt {\n"
"  YisStr* key;\n"
"  YisVal val;\n"
"} YisDictEnt;\n"
"\n"
"typedef struct YisDict {\n"
"  int ref;\n"
"  size_t len;\n"
"  size_t cap;\n"
"  YisDictEnt* entries;\n"
"} YisDict;\n"
"\n"
"typedef struct YisObj {\n"
"  int ref;\n"
"  void (*drop)(struct YisObj*);\n"
"} YisObj;\n"
"\n"
"typedef struct YisFn {\n"
"  int ref;\n"
"  int arity;\n"
"  YisVal (*fn)(void* env, int argc, YisVal* argv);\n"
"  void* env;\n"
"  int env_size;\n"
"} YisFn;\n"
"\n"
"typedef struct YisRef {\n"
"  int ref;\n"
"  YisVal val;\n"
"} YisRef;\n"
"\n"
"static int stdr_len(YisVal v);\n"
"static int64_t stdr_num(YisVal v);\n"
"\n"
"#define YV_NULLV ((YisVal){.tag=EVT_NULL})\n"
"#define YV_INT(x) ((YisVal){.tag=EVT_INT, .as.i=(int64_t)(x)})\n"
"#define YV_FLOAT(x) ((YisVal){.tag=EVT_FLOAT, .as.f=(double)(x)})\n"
"#define YV_BOOL(x) ((YisVal){.tag=EVT_BOOL, .as.b=(x)?true:false})\n"
"#define YV_STR(x) ((YisVal){.tag=EVT_STR, .as.p=(x)})\n"
"#define YV_ARR(x) ((YisVal){.tag=EVT_ARR, .as.p=(x)})\n"
"#define YV_DICT(x) ((YisVal){.tag=EVT_DICT, .as.p=(x)})\n"
"#define YV_OBJ(x) ((YisVal){.tag=EVT_OBJ, .as.p=(x)})\n"
"#define YV_FN(x) ((YisVal){.tag=EVT_FN, .as.p=(x)})\n"
"\n"
"static void yis_trap(const char* msg) {\n"
"  fprintf(stderr, \"runtime error: %s\\n\", msg ? msg : \"unknown error\");\n"
"  fprintf(stderr, \"  (run with debugger for stack trace)\\n\");\n"
"  abort();\n"
"}\n"
"\n"
"static void yis_retain_val(YisVal v);\n"
"static void yis_release_val(YisVal v);\n"
"static int64_t yis_as_int(YisVal v);\n"
"static YisRef* yis_ref_new(void);\n"
"static void yis_ref_retain(YisRef* r);\n"
"static void yis_ref_release(YisRef* r);\n"
"\n"
"// Static constant strings (ref=INT32_MAX means never freed)\n"
"static YisStr yis_static_empty    = { INT32_MAX, 0, \"\" };\n"
"static YisStr yis_static_null     = { INT32_MAX, 4, \"null\" };\n"
"static YisStr yis_static_true     = { INT32_MAX, 4, \"true\" };\n"
"static YisStr yis_static_false    = { INT32_MAX, 5, \"false\" };\n"
"static YisStr yis_static_array    = { INT32_MAX, 7, \"[array]\" };\n"
"static YisStr yis_static_dict     = { INT32_MAX, 6, \"[dict]\" };\n"
"static YisStr yis_static_object   = { INT32_MAX, 8, \"[object]\" };\n"
"static YisStr yis_static_function = { INT32_MAX, 10, \"[function]\" };\n"
"static YisStr yis_static_unknown  = { INT32_MAX, 3, \"<?>\" };\n"
"\n"
"static bool yis_static_ascii_init = false;\n"
"static YisStr yis_static_ascii[256];\n"
"static char yis_static_ascii_data[256][2];\n"
"\n"
"static void yis_init_static_ascii(void) {\n"
"  if (yis_static_ascii_init) return;\n"
"  for (int i = 0; i < 256; i++) {\n"
"    yis_static_ascii_data[i][0] = (char)i;\n"
"    yis_static_ascii_data[i][1] = 0;\n"
"    yis_static_ascii[i].ref = INT32_MAX;\n"
"    yis_static_ascii[i].len = 1;\n"
"    yis_static_ascii[i].data = yis_static_ascii_data[i];\n"
"  }\n"
"  yis_static_ascii_init = true;\n"
"}\n"
"\n"
"static YisStr* yis_static_char(unsigned char c) {\n"
"  if (!yis_static_ascii_init) yis_init_static_ascii();\n"
"  return &yis_static_ascii[c];\n"
"}\n"
"\n"
"static YisStr* stdr_str_lit(const char* s) {\n"
"  size_t n = strlen(s);\n"
"  if (n == 0) return &yis_static_empty;\n"
"  if (n == 1) return yis_static_char((unsigned char)s[0]);\n"
"  YisStr* st = (YisStr*)malloc(sizeof(YisStr) + n + 1);\n"
"  st->ref = 1;\n"
"  st->len = n;\n"
"  st->data = (char*)(st + 1);\n"
"  memcpy(st->data, s, n + 1);\n"
"  return st;\n"
"}\n"
"\n"
"static YisStr* stdr_str_from_parts(int n, YisVal* parts);\n"
"static YisStr* stdr_to_string(YisVal v);\n"
"static YisStr* stdr_str_from_slice(const char* s, size_t len);\n"
"static YisArr* stdr_arr_new(int n);\n"
"static void yis_arr_add(YisArr* a, YisVal v);\n"
"static YisVal yis_arr_get(YisArr* a, int64_t idx);\n"
"static void yis_arr_set(YisArr* a, int64_t idx, YisVal v);\n"
"static YisVal yis_arr_remove(YisArr* a, int64_t idx);\n"
"\n"
"static YisDict* stdr_dict_new(void);\n"
"static void yis_dict_set(YisDict* d, YisVal key, YisVal val);\n"
"static YisVal yis_dict_get(YisDict* d, YisVal key);\n"
"static int yis_dict_len(YisDict* d);\n"
"\n"
"static YisVal stdr_str_at(YisVal v, int64_t idx) {\n"
"  if (v.tag != EVT_STR) yis_trap(\"str_at expects string\");\n"
"  YisStr* s = (YisStr*)v.as.p;\n"
"  if (idx < 0 || (size_t)idx >= s->len) return YV_STR(&yis_static_empty);\n"
"  return YV_STR(yis_static_char((unsigned char)s->data[idx]));\n"
"}\n"
"\n"
"static YisVal stdr_slice(YisVal sv, int64_t start, int64_t end) {\n"
"  if (sv.tag != EVT_STR) yis_trap(\"slice expects string\");\n"
"  YisStr* s = (YisStr*)sv.as.p;\n"
"  size_t len = s->len;\n"
"  if (start < 0) start = 0;\n"
"  if ((size_t)start > len) start = (int64_t)len;\n"
"  if (end < start) end = start;\n"
"  if ((size_t)end > len) end = (int64_t)len;\n"
"  size_t n = (size_t)(end - start);\n"
"  if (n == 0) return YV_STR(&yis_static_empty);\n"
"  if (n == 1) return YV_STR(yis_static_char((unsigned char)s->data[start]));\n"
"  return YV_STR(stdr_str_from_slice(s->data + start, n));\n"
"}\n"
"\n"
"static YisVal stdr_str_concat(YisVal a, YisVal b) {\n"
"  YisVal parts[2] = { a, b };\n"
"  return YV_STR(stdr_str_from_parts(2, parts));\n"
"}\n"
"\n"
"static int64_t stdr_char_code(YisVal cv) {\n"
"  if (cv.tag != EVT_STR) yis_trap(\"char_code expects string\");\n"
"  YisStr* s = (YisStr*)cv.as.p;\n"
"  if (s->len == 0) return 0;\n"
"  return (unsigned char)s->data[0];\n"
"}\n"
"\n"
"static int stdr_len(YisVal v) {\n"
"  if (v.tag == EVT_STR) return (int)((YisStr*)v.as.p)->len;\n"
"  if (v.tag == EVT_ARR) return (int)((YisArr*)v.as.p)->len;\n"
"  if (v.tag == EVT_DICT) return (int)((YisDict*)v.as.p)->len;\n"
"  return 0;\n"
"}\n"
"\n"
"static int64_t stdr_num(YisVal v) {\n"
"  return yis_as_int(v);\n"
"}\n"
"\n"
"static bool stdr_is_null(YisVal v) { return v.tag == EVT_NULL; }\n"
"\n"
"static void stdr_write(YisVal v) {\n"
"  YisStr* s = stdr_to_string(v);\n"
"  fwrite(s->data, 1, s->len, stdout);\n"
"  fflush(stdout);\n"
"  yis_release_val(YV_STR(s));\n"
"}\n"
"\n"
"static void writef(YisVal fmt, int argc, YisVal* argv) {\n"
"  if (fmt.tag != EVT_STR) yis_trap(\"writef expects string\");\n"
"  YisStr* s = (YisStr*)fmt.as.p;\n"
"  size_t i = 0;\n"
"  size_t seg = 0;\n"
"  int argi = 0;\n"
"  while (i < s->len) {\n"
"    if (i + 1 < s->len && s->data[i] == '{' && s->data[i + 1] == '}') {\n"
"      if (i > seg) fwrite(s->data + seg, 1, i - seg, stdout);\n"
"      if (argi < argc) {\n"
"        YisStr* ps = stdr_to_string(argv[argi++]);\n"
"        fwrite(ps->data, 1, ps->len, stdout);\n"
"        yis_release_val(YV_STR(ps));\n"
"      }\n"
"      i += 2;\n"
"      seg = i;\n"
"      continue;\n"
"    }\n"
"    i++;\n"
"  }\n"
"  if (i > seg) fwrite(s->data + seg, 1, i - seg, stdout);\n"
"  if (yis_stdout_isatty) fflush(stdout);\n"
"}\n"
"\n"
"static void stdr_writef_args(YisVal fmt, YisVal args) {\n"
"  if (args.tag != EVT_ARR) yis_trap(\"writef expects args tuple\");\n"
"  YisArr* a = (YisArr*)args.as.p;\n"
"  writef(fmt, (int)a->len, a->items);\n"
"}\n"
"\n"
"static YisStr* stdr_read_line(void) {\n"
"  size_t cap = 128;\n"
"  size_t len = 0;\n"
"  char* buf = (char*)malloc(cap);\n"
"  if (!buf) yis_trap(\"out of memory\");\n"
"  int c;\n"
"  while ((c = fgetc(stdin)) != EOF) {\n"
"    if (c == '\\n') break;\n"
"    if (len + 1 >= cap) {\n"
"      cap *= 2;\n"
"      buf = (char*)realloc(buf, cap);\n"
"      if (!buf) yis_trap(\"out of memory\");\n"
"    }\n"
"    buf[len++] = (char)c;\n"
"  }\n"
"  if (len > 0 && buf[len - 1] == '\\r') len--;\n"
"  YisStr* s = (YisStr*)malloc(sizeof(YisStr) + len + 1);\n"
"  if (!s) yis_trap(\"out of memory\");\n"
"  s->ref = 1;\n"
"  s->len = len;\n"
"  s->data = (char*)(s + 1);\n"
"  memcpy(s->data, buf, len);\n"
"  s->data[len] = 0;\n"
"  free(buf);\n"
"  return s;\n"
"}\n"
"\n"
"static YisVal stdr_read_text_file(YisVal pathv) {\n"
"  if (pathv.tag != EVT_STR) yis_trap(\"read_text_file expects string path\");\n"
"  YisStr* path = (YisStr*)pathv.as.p;\n"
"  FILE* f = fopen(path->data, \"rb\");\n"
"  if (!f) return YV_NULLV;\n"
"  if (fseek(f, 0, SEEK_END) != 0) {\n"
"    fclose(f);\n"
"    return YV_NULLV;\n"
"  }\n"
"  long sz = ftell(f);\n"
"  if (sz < 0) {\n"
"    fclose(f);\n"
"    return YV_NULLV;\n"
"  }\n"
"  if (fseek(f, 0, SEEK_SET) != 0) {\n"
"    fclose(f);\n"
"    return YV_NULLV;\n"
"  }\n"
"  size_t len = (size_t)sz;\n"
"  YisStr* out = (YisStr*)malloc(sizeof(YisStr) + len + 1);\n"
"  if (!out) {\n"
"    fclose(f);\n"
"    yis_trap(\"out of memory\");\n"
"  }\n"
"  out->data = (char*)(out + 1);\n"
"  size_t n = 0;\n"
"  if (len > 0) n = fread(out->data, 1, len, f);\n"
"  fclose(f);\n"
"  if (n != len) {\n"
"    free(out);\n"
"    return YV_NULLV;\n"
"  }\n"
"  out->ref = 1;\n"
"  out->len = len;\n"
"  out->data[len] = 0;\n"
"  return YV_STR(out);\n"
"}\n"
"\n"
"static YisVal stdr_write_text_file(YisVal pathv, YisVal textv) {\n"
"  if (pathv.tag != EVT_STR) yis_trap(\"write_text_file expects string path\");\n"
"  if (textv.tag != EVT_STR) yis_trap(\"write_text_file expects string text\");\n"
"  YisStr* path = (YisStr*)pathv.as.p;\n"
"  YisStr* text = (YisStr*)textv.as.p;\n"
"  FILE* f = fopen(path->data, \"wb\");\n"
"  if (!f) return YV_BOOL(false);\n"
"  size_t n = 0;\n"
"  if (text->len > 0) n = fwrite(text->data, 1, text->len, f);\n"
"  bool ok = (n == text->len) && (fclose(f) == 0);\n"
"  return YV_BOOL(ok);\n"
"}\n"
"\n"
"static bool stdr_is_dir_path(const char* path) {\n"
"  if (!path || !path[0]) return false;\n"
"  struct stat st;\n"
"  if (stat(path, &st) != 0) return false;\n"
"  return S_ISDIR(st.st_mode);\n"
"}\n"
"\n"
"static int stdr_mkdir_single(const char* path) {\n"
"#if defined(_WIN32)\n"
"  if (_mkdir(path) == 0) return 0;\n"
"#else\n"
"  if (mkdir(path, 0755) == 0) return 0;\n"
"#endif\n"
"  if (errno == EEXIST && stdr_is_dir_path(path)) return 0;\n"
"  return -1;\n"
"}\n"
"\n"
"static YisVal stdr_ensure_dir(YisVal pathv) {\n"
"  if (pathv.tag != EVT_STR) yis_trap(\"ensure_dir expects string path\");\n"
"  YisStr* path = (YisStr*)pathv.as.p;\n"
"  if (!path || path->len == 0) return YV_BOOL(false);\n"
"\n"
"  size_t len = path->len;\n"
"  char* buf = (char*)malloc(len + 2);\n"
"  if (!buf) yis_trap(\"out of memory\");\n"
"  memcpy(buf, path->data, len);\n"
"  buf[len] = 0;\n"
"\n"
"  while (len > 1 && (buf[len - 1] == '/' || buf[len - 1] == '\\\\')) {\n"
"    buf[len - 1] = 0;\n"
"    len--;\n"
"  }\n"
"  if (len == 0) {\n"
"    free(buf);\n"
"    return YV_BOOL(false);\n"
"  }\n"
"\n"
"  size_t start = 0;\n"
"#if defined(_WIN32)\n"
"  if (len >= 2 &&\n"
"      (((buf[0] >= 'A' && buf[0] <= 'Z') || (buf[0] >= 'a' && buf[0] <= 'z')) &&\n"
"       buf[1] == ':')) {\n"
"    start = 2;\n"
"  }\n"
"#endif\n"
"  if (buf[0] == '/' || buf[0] == '\\\\') start = 1;\n"
"\n"
"  for (size_t i = start; i <= len; i++) {\n"
"    char ch = buf[i];\n"
"    if (ch != '/' && ch != '\\\\' && ch != 0) continue;\n"
"    buf[i] = 0;\n"
"    if (buf[0] != 0) {\n"
"      if (stdr_mkdir_single(buf) != 0) {\n"
"        free(buf);\n"
"        return YV_BOOL(false);\n"
"      }\n"
"    }\n"
"    buf[i] = ch;\n"
"  }\n"
"\n"
"  free(buf);\n"
"  return YV_BOOL(true);\n"
"}\n"
"\n"
"static YisVal stdr_remove_file(YisVal pathv) {\n"
"  if (pathv.tag != EVT_STR) yis_trap(\"remove_file expects string path\");\n"
"  YisStr* path = (YisStr*)pathv.as.p;\n"
"  if (!path || path->len == 0) return YV_BOOL(false);\n"
"#if defined(_WIN32)\n"
"  if (_unlink(path->data) == 0) return YV_BOOL(true);\n"
"#else\n"
"  if (unlink(path->data) == 0) return YV_BOOL(true);\n"
"#endif\n"
"  if (errno == ENOENT) return YV_BOOL(true);\n"
"  return YV_BOOL(false);\n"
"}\n"
"\n"
"static YisVal stdr_move_file(YisVal srcv, YisVal dstv) {\n"
"  if (srcv.tag != EVT_STR) yis_trap(\"move_file expects source path string\");\n"
"  if (dstv.tag != EVT_STR) yis_trap(\"move_file expects destination path string\");\n"
"  YisStr* src = (YisStr*)srcv.as.p;\n"
"  YisStr* dst = (YisStr*)dstv.as.p;\n"
"  if (!src || src->len == 0 || !dst || dst->len == 0) return YV_BOOL(false);\n"
"#if defined(_WIN32)\n"
"  _unlink(dst->data);\n"
"#endif\n"
"  if (rename(src->data, dst->data) == 0) return YV_BOOL(true);\n"
"  return YV_BOOL(false);\n"
"}\n"
"\n"
"static bool stdr_ends_with_ci(const char* text, const char* suffix) {\n"
"  if (!text || !suffix) return false;\n"
"  size_t tn = strlen(text);\n"
"  size_t sn = strlen(suffix);\n"
"  if (sn == 0 || sn > tn) return false;\n"
"  const char* t = text + (tn - sn);\n"
"  for (size_t i = 0; i < sn; i++) {\n"
"    unsigned char a = (unsigned char)t[i];\n"
"    unsigned char b = (unsigned char)suffix[i];\n"
"    if ((unsigned char)tolower(a) != (unsigned char)tolower(b)) return false;\n"
"  }\n"
"  return true;\n"
"}\n"
"\n"
"static bool stdr_name_matches_exts(const char* name, YisArr* exts) {\n"
"  if (!name || !exts) return false;\n"
"  for (size_t i = 0; i < exts->len; i++) {\n"
"    YisVal ev = exts->items[i];\n"
"    if (ev.tag != EVT_STR) continue;\n"
"    YisStr* ext = (YisStr*)ev.as.p;\n"
"    if (!ext || ext->len == 0) continue;\n"
"    if (stdr_ends_with_ci(name, ext->data)) return true;\n"
"  }\n"
"  return false;\n"
"}\n"
"\n"
"static char* stdr_join_path_c(const char* dir, const char* name) {\n"
"  if (!dir || !name) return NULL;\n"
"  size_t dl = strlen(dir);\n"
"  size_t nl = strlen(name);\n"
"  bool need_sep = (dl > 0 && dir[dl - 1] != '/');\n"
"  size_t total = dl + (need_sep ? 1 : 0) + nl + 1;\n"
"  char* out = (char*)malloc(total);\n"
"  if (!out) return NULL;\n"
"  memcpy(out, dir, dl);\n"
"  size_t p = dl;\n"
"  if (need_sep) out[p++] = '/';\n"
"  memcpy(out + p, name, nl);\n"
"  out[p + nl] = 0;\n"
"  return out;\n"
"}\n"
"\n"
"static int stdr_cmp_paths(const void* a, const void* b) {\n"
"  const YisVal* va = (const YisVal*)a;\n"
"  const YisVal* vb = (const YisVal*)b;\n"
"  if (va->tag != EVT_STR || vb->tag != EVT_STR) return 0;\n"
"  YisStr* sa = (YisStr*)va->as.p;\n"
"  YisStr* sb = (YisStr*)vb->as.p;\n"
"  const char* pa = (sa && sa->data) ? sa->data : \"\";\n"
"  const char* pb = (sb && sb->data) ? sb->data : \"\";\n"
"  return strcmp(pa, pb);\n"
"}\n"
"\n"
"#if !defined(_WIN32)\n"
"static int64_t stdr_stat_mtime_secs(const struct stat* st) {\n"
"#if defined(__APPLE__)\n"
"  return (int64_t)st->st_mtimespec.tv_sec;\n"
"#elif defined(_WIN32)\n"
"  return (int64_t)st->st_mtime;\n"
"#else\n"
"  return (int64_t)st->st_mtim.tv_sec;\n"
"#endif\n"
"}\n"
"\n"
"static void stdr_find_files_walk(const char* dir, YisArr* exts, YisArr* out) {\n"
"  DIR* dp = opendir(dir);\n"
"  if (!dp) return;\n"
"  struct dirent* ent = NULL;\n"
"  while ((ent = readdir(dp)) != NULL) {\n"
"    const char* name = ent->d_name;\n"
"    if (!name) continue;\n"
"    if (strcmp(name, \".\") == 0 || strcmp(name, \"..\") == 0) continue;\n"
"\n"
"    char* full = stdr_join_path_c(dir, name);\n"
"    if (!full) continue;\n"
"\n"
"    struct stat st;\n"
"    if (lstat(full, &st) == 0) {\n"
"      if (S_ISDIR(st.st_mode)) {\n"
"        stdr_find_files_walk(full, exts, out);\n"
"      } else if (S_ISREG(st.st_mode) && stdr_name_matches_exts(name, exts)) {\n"
"        yis_arr_add(out, YV_STR(stdr_str_from_slice(full, strlen(full))));\n"
"      }\n"
"    }\n"
"    free(full);\n"
"  }\n"
"  closedir(dp);\n"
"}\n"
"\n"
"static void stdr_prune_old_files_walk(const char* dir, int64_t cutoff, int64_t* removed) {\n"
"  DIR* dp = opendir(dir);\n"
"  if (!dp) return;\n"
"  struct dirent* ent = NULL;\n"
"  while ((ent = readdir(dp)) != NULL) {\n"
"    const char* name = ent->d_name;\n"
"    if (!name) continue;\n"
"    if (strcmp(name, \".\") == 0 || strcmp(name, \"..\") == 0) continue;\n"
"\n"
"    char* full = stdr_join_path_c(dir, name);\n"
"    if (!full) continue;\n"
"\n"
"    struct stat st;\n"
"    if (lstat(full, &st) == 0) {\n"
"      if (S_ISDIR(st.st_mode)) {\n"
"        stdr_prune_old_files_walk(full, cutoff, removed);\n"
"      } else if (S_ISREG(st.st_mode)) {\n"
"        int64_t mt = stdr_stat_mtime_secs(&st);\n"
"        if (mt <= cutoff && unlink(full) == 0) {\n"
"          if (removed) (*removed)++;\n"
"        }\n"
"      }\n"
"    }\n"
"    free(full);\n"
"  }\n"
"  closedir(dp);\n"
"}\n"
"#endif\n"
"\n"
"static YisVal stdr_find_files(YisVal rootv, YisVal extsv) {\n"
"  if (rootv.tag != EVT_STR) yis_trap(\"find_files expects root path string\");\n"
"  if (extsv.tag != EVT_ARR) yis_trap(\"find_files expects extensions array\");\n"
"  YisStr* root = (YisStr*)rootv.as.p;\n"
"  YisArr* exts = (YisArr*)extsv.as.p;\n"
"  YisArr* out = stdr_arr_new(8);\n"
"  if (!root || root->len == 0 || !exts) return YV_ARR(out);\n"
"\n"
"#if !defined(_WIN32)\n"
"  struct stat st;\n"
"  if (stat(root->data, &st) == 0 && S_ISDIR(st.st_mode)) {\n"
"    stdr_find_files_walk(root->data, exts, out);\n"
"  }\n"
"#else\n"
"  (void)root;\n"
"  (void)exts;\n"
"#endif\n"
"\n"
"  if (out->len > 1) {\n"
"    qsort(out->items, out->len, sizeof(YisVal), stdr_cmp_paths);\n"
"  }\n"
"  return YV_ARR(out);\n"
"}\n"
"\n"
"static YisVal stdr_prune_files_older_than(YisVal dirv, YisVal daysv) {\n"
"  if (dirv.tag != EVT_STR) yis_trap(\"prune_files_older_than expects directory path string\");\n"
"  YisStr* dir = (YisStr*)dirv.as.p;\n"
"  int64_t days = stdr_num(daysv);\n"
"  if (!dir || dir->len == 0 || days <= 0) return YV_INT(0);\n"
"\n"
"  time_t now = time(NULL);\n"
"  if (now == (time_t)-1) return YV_INT(0);\n"
"  int64_t cutoff = (int64_t)now - (days * 86400);\n"
"  int64_t removed = 0;\n"
"\n"
"#if !defined(_WIN32)\n"
"  struct stat st;\n"
"  if (stat(dir->data, &st) == 0 && S_ISDIR(st.st_mode)) {\n"
"    stdr_prune_old_files_walk(dir->data, cutoff, &removed);\n"
"  }\n"
"#else\n"
"  (void)dir;\n"
"  (void)cutoff;\n"
"#endif\n"
"\n"
"  return YV_INT(removed);\n"
"}\n"
"\n"
"static YisVal stdr_run_command(YisVal cmdv) {\n"
"  if (cmdv.tag != EVT_STR) yis_trap(\"run_command expects string\");\n"
"  YisStr* cmd = (YisStr*)cmdv.as.p;\n"
"#if defined(_WIN32)\n"
"  FILE* p = _popen(cmd->data, \"r\");\n"
"#else\n"
"  FILE* p = popen(cmd->data, \"r\");\n"
"#endif\n"
"  if (!p) {\n"
"    YisArr* out = stdr_arr_new(2);\n"
"    yis_arr_add(out, YV_INT(-1));\n"
"    yis_arr_add(out, YV_STR(stdr_str_lit(\"\")));\n"
"    return YV_ARR(out);\n"
"  }\n"
"  size_t cap = 4096;\n"
"  size_t len = 0;\n"
"  char* buf = (char*)malloc(cap);\n"
"  if (!buf) {\n"
"#if defined(_WIN32)\n"
"    _pclose(p);\n"
"#else\n"
"    pclose(p);\n"
"#endif\n"
"    yis_trap(\"out of memory\");\n"
"  }\n"
"  int c;\n"
"  while ((c = fgetc(p)) != EOF) {\n"
"    if (len + 1 >= cap) {\n"
"      cap *= 2;\n"
"      char* n = (char*)realloc(buf, cap);\n"
"      if (!n) {\n"
"        free(buf);\n"
"#if defined(_WIN32)\n"
"        _pclose(p);\n"
"#else\n"
"        pclose(p);\n"
"#endif\n"
"        yis_trap(\"out of memory\");\n"
"      }\n"
"      buf = n;\n"
"    }\n"
"    buf[len++] = (char)c;\n"
"  }\n"
"  buf[len] = '\\0';\n"
"#if defined(_WIN32)\n"
"  int status = _pclose(p);\n"
"#else\n"
"  int status = pclose(p);\n"
"#endif\n"
"  YisStr* out_str = stdr_str_from_slice(buf, len);\n"
"  free(buf);\n"
"  YisArr* out = stdr_arr_new(2);\n"
"  yis_arr_add(out, YV_INT(status));\n"
"  yis_arr_add(out, YV_STR(out_str));\n"
"  YisVal rv; rv.tag = EVT_ARR; rv.as.p = out;\n"
"  return rv;\n"
"}\n"
"\n"
"static YisVal stdr_file_exists(YisVal pathv) {\n"
"  if (pathv.tag != EVT_STR) yis_trap(\"file_exists expects string\");\n"
"  YisStr* s = (YisStr*)pathv.as.p;\n"
"  struct stat st;\n"
"  return YV_BOOL(stat(s->data, &st) == 0 && S_ISREG(st.st_mode));\n"
"}\n"
"\n"
"static YisVal stdr_file_mtime(YisVal pathv) {\n"
"  if (pathv.tag != EVT_STR) yis_trap(\"file_mtime expects string\");\n"
"  YisStr* s = (YisStr*)pathv.as.p;\n"
"  struct stat st;\n"
"  if (stat(s->data, &st) != 0) return YV_INT(-1);\n"
"#if defined(__APPLE__)\n"
"  return YV_INT((int64_t)st.st_mtimespec.tv_sec);\n"
"#elif defined(_WIN32)\n"
"  return YV_INT((int64_t)st.st_mtime);\n"
"#else\n"
"  return YV_INT((int64_t)st.st_mtim.tv_sec);\n"
"#endif\n"
"}\n"
"\n"
"static YisVal stdr_getcwd(void) {\n"
"  char buf[4096];\n"
"  if (getcwd(buf, sizeof(buf))) return YV_STR(stdr_str_from_slice(buf, strlen(buf)));\n"
"  return YV_STR(stdr_str_from_slice(\"\", 0));\n"
"}\n"
"\n"
"static YisVal stdr_home_dir(void) {\n"
"  const char* home = getenv(\"HOME\");\n"
"#if defined(_WIN32)\n"
"  if (!home || !home[0]) home = getenv(\"USERPROFILE\");\n"
"#endif\n"
"  if (!home) home = \"\";\n"
"  return YV_STR(stdr_str_from_slice(home, strlen(home)));\n"
"}\n"
"\n"
"static bool stdr_localtime_safe(time_t ts, struct tm* out_tm) {\n"
"  if (!out_tm) return false;\n"
"#if defined(_WIN32)\n"
"  return localtime_s(out_tm, &ts) == 0;\n"
"#else\n"
"  return localtime_r(&ts, out_tm) != NULL;\n"
"#endif\n"
"}\n"
"\n"
"static YisVal stdr_unix_time(void) {\n"
"  time_t now = time(NULL);\n"
"  if (now == (time_t)-1) return YV_INT(-1);\n"
"  return YV_INT((int64_t)now);\n"
"}\n"
"\n"
"static YisVal stdr_current_year(void) {\n"
"  time_t now = time(NULL);\n"
"  struct tm tmv;\n"
"  if (now == (time_t)-1 || !stdr_localtime_safe(now, &tmv)) return YV_INT(0);\n"
"  return YV_INT((int64_t)(tmv.tm_year + 1900));\n"
"}\n"
"\n"
"static YisVal stdr_current_month(void) {\n"
"  time_t now = time(NULL);\n"
"  struct tm tmv;\n"
"  if (now == (time_t)-1 || !stdr_localtime_safe(now, &tmv)) return YV_INT(0);\n"
"  return YV_INT((int64_t)(tmv.tm_mon + 1));\n"
"}\n"
"\n"
"static YisVal stdr_current_day(void) {\n"
"  time_t now = time(NULL);\n"
"  struct tm tmv;\n"
"  if (now == (time_t)-1 || !stdr_localtime_safe(now, &tmv)) return YV_INT(0);\n"
"  return YV_INT((int64_t)tmv.tm_mday);\n"
"}\n"
"\n"
"static YisVal stdr_weekday(YisVal yearv, YisVal monthv, YisVal dayv) {\n"
"  int y = (int)stdr_num(yearv);\n"
"  int m = (int)stdr_num(monthv);\n"
"  int d = (int)stdr_num(dayv);\n"
"  if (y < 1 || m < 1 || m > 12 || d < 1 || d > 31) return YV_INT(0);\n"
"\n"
"  struct tm tmv;\n"
"  memset(&tmv, 0, sizeof(tmv));\n"
"  tmv.tm_year = y - 1900;\n"
"  tmv.tm_mon = m - 1;\n"
"  tmv.tm_mday = d;\n"
"  tmv.tm_hour = 12;\n"
"  tmv.tm_isdst = -1;\n"
"\n"
"  time_t ts = mktime(&tmv);\n"
"  if (ts == (time_t)-1) return YV_INT(0);\n"
"  struct tm out_tm;\n"
"  if (!stdr_localtime_safe(ts, &out_tm)) return YV_INT(0);\n"
"  return YV_INT((int64_t)out_tm.tm_wday);\n"
"}\n"
"\n"
"static bool stdr_parse_iso_ymdhm(const char* s, int* y, int* m, int* d, int* hh, int* mm) {\n"
"  if (!s || !y || !m || !d || !hh || !mm) return false;\n"
"  if (strlen(s) < 16) return false;\n"
"  if (s[4] != '-' || s[7] != '-' || s[10] != 'T' || s[13] != ':') return false;\n"
"\n"
"  for (int i = 0; i < 16; i++) {\n"
"    if (i == 4 || i == 7 || i == 10 || i == 13) continue;\n"
"    if (!isdigit((unsigned char)s[i])) return false;\n"
"  }\n"
"\n"
"  *y = (s[0] - '0') * 1000 + (s[1] - '0') * 100 + (s[2] - '0') * 10 + (s[3] - '0');\n"
"  *m = (s[5] - '0') * 10 + (s[6] - '0');\n"
"  *d = (s[8] - '0') * 10 + (s[9] - '0');\n"
"  *hh = (s[11] - '0') * 10 + (s[12] - '0');\n"
"  *mm = (s[14] - '0') * 10 + (s[15] - '0');\n"
"\n"
"  if (*m < 1 || *m > 12 || *d < 1 || *d > 31 || *hh < 0 || *hh > 23 || *mm < 0 || *mm > 59) {\n"
"    return false;\n"
"  }\n"
"  return true;\n"
"}\n"
"\n"
"static int64_t stdr_mktime_with_tz(struct tm* tmv, const char* tz_name) {\n"
"  if (!tmv) return -1;\n"
"#if defined(_WIN32)\n"
"  if (tz_name && tz_name[0]) {\n"
"    _putenv_s(\"TZ\", tz_name);\n"
"  } else {\n"
"    _putenv_s(\"TZ\", \"\");\n"
"  }\n"
"  _tzset();\n"
"  time_t ts = mktime(tmv);\n"
"  _putenv_s(\"TZ\", \"\");\n"
"  _tzset();\n"
"  if (ts == (time_t)-1) return -1;\n"
"  return (int64_t)ts;\n"
"#else\n"
"  char* old_tz = getenv(\"TZ\");\n"
"  char* old_copy = old_tz ? strdup(old_tz) : NULL;\n"
"  if (tz_name && tz_name[0]) {\n"
"    setenv(\"TZ\", tz_name, 1);\n"
"  } else {\n"
"    unsetenv(\"TZ\");\n"
"  }\n"
"  tzset();\n"
"\n"
"  time_t ts = mktime(tmv);\n"
"\n"
"  if (old_copy) {\n"
"    setenv(\"TZ\", old_copy, 1);\n"
"    free(old_copy);\n"
"  } else {\n"
"    unsetenv(\"TZ\");\n"
"  }\n"
"  tzset();\n"
"\n"
"  if (ts == (time_t)-1) return -1;\n"
"  return (int64_t)ts;\n"
"#endif\n"
"}\n"
"\n"
"static YisVal stdr_iso_to_epoch(YisVal isov, YisVal tzv) {\n"
"  if (isov.tag != EVT_STR) yis_trap(\"iso_to_epoch expects iso string\");\n"
"  if (tzv.tag != EVT_STR && tzv.tag != EVT_NULL) yis_trap(\"iso_to_epoch expects timezone string\");\n"
"\n"
"  YisStr* iso = (YisStr*)isov.as.p;\n"
"  if (!iso || iso->len == 0) return YV_INT(-1);\n"
"\n"
"  int y = 0, m = 0, d = 0, hh = 0, mm = 0;\n"
"  if (!stdr_parse_iso_ymdhm(iso->data, &y, &m, &d, &hh, &mm)) return YV_INT(-1);\n"
"\n"
"  struct tm tmv;\n"
"  memset(&tmv, 0, sizeof(tmv));\n"
"  tmv.tm_year = y - 1900;\n"
"  tmv.tm_mon = m - 1;\n"
"  tmv.tm_mday = d;\n"
"  tmv.tm_hour = hh;\n"
"  tmv.tm_min = mm;\n"
"  tmv.tm_sec = 0;\n"
"  tmv.tm_isdst = -1;\n"
"\n"
"  const char* tz_name = \"\";\n"
"  if (tzv.tag == EVT_STR) {\n"
"    YisStr* tz = (YisStr*)tzv.as.p;\n"
"    if (tz && tz->len > 0) tz_name = tz->data;\n"
"  }\n"
"\n"
"  return YV_INT(stdr_mktime_with_tz(&tmv, tz_name));\n"
"}\n"
"\n"
"static YisVal stdr_capture_shell_first_line(const char* cmd) {\n"
"  if (!cmd || !cmd[0]) return YV_NULLV;\n"
"#if defined(_WIN32)\n"
"  FILE* p = _popen(cmd, \"r\");\n"
"#else\n"
"  FILE* p = popen(cmd, \"r\");\n"
"#endif\n"
"  if (!p) return YV_NULLV;\n"
"  char buf[4096];\n"
"  if (!fgets(buf, sizeof(buf), p)) {\n"
"#if defined(_WIN32)\n"
"    _pclose(p);\n"
"#else\n"
"    pclose(p);\n"
"#endif\n"
"    return YV_NULLV;\n"
"  }\n"
"#if defined(_WIN32)\n"
"  _pclose(p);\n"
"#else\n"
"  pclose(p);\n"
"#endif\n"
"  size_t len = strlen(buf);\n"
"  while (len > 0 && (buf[len - 1] == '\\n' || buf[len - 1] == '\\r')) len--;\n"
"  if (len == 0) return YV_NULLV;\n"
"  return YV_STR(stdr_str_from_slice(buf, len));\n"
"}\n"
"\n"
"static YisVal stdr_open_file_dialog(YisVal promptv, YisVal extv) {\n"
"  if (promptv.tag != EVT_STR) yis_trap(\"open_file_dialog expects prompt string\");\n"
"  if (extv.tag != EVT_STR) yis_trap(\"open_file_dialog expects extension string\");\n"
"  YisStr* prompt = (YisStr*)promptv.as.p;\n"
"  YisStr* ext = (YisStr*)extv.as.p;\n"
"#if defined(__APPLE__)\n"
"  char cmd[8192];\n"
"  snprintf(cmd, sizeof(cmd),\n"
"           \"osascript -e 'set _p to POSIX path of (choose file of type {\\\"%s\\\"} with prompt \\\"%s\\\")' -e 'return _p' 2>/dev/null\",\n"
"           ext ? ext->data : \"\", prompt ? prompt->data : \"\");\n"
"  return stdr_capture_shell_first_line(cmd);\n"
"#elif defined(__linux__)\n"
"  char cmd[8192];\n"
"  if (ext && ext->data && ext->data[0]) {\n"
"    snprintf(cmd, sizeof(cmd),\n"
"             \"zenity --file-selection --title=\\\"%s\\\" --file-filter=\\\"*.%s\\\" 2>/dev/null\",\n"
"             prompt ? prompt->data : \"Open\", ext->data);\n"
"  } else {\n"
"    snprintf(cmd, sizeof(cmd),\n"
"             \"zenity --file-selection --title=\\\"%s\\\" 2>/dev/null\",\n"
"             prompt ? prompt->data : \"Open\");\n"
"  }\n"
"  return stdr_capture_shell_first_line(cmd);\n"
"#else\n"
"  (void)prompt;\n"
"  (void)ext;\n"
"  return YV_NULLV;\n"
"#endif\n"
"}\n"
"\n"
"static YisVal stdr_open_folder_dialog(YisVal promptv) {\n"
"  if (promptv.tag != EVT_STR) yis_trap(\"open_folder_dialog expects prompt string\");\n"
"  YisStr* prompt = (YisStr*)promptv.as.p;\n"
"#if defined(__APPLE__)\n"
"  char cmd[8192];\n"
"  snprintf(cmd, sizeof(cmd),\n"
"           \"osascript -e 'set _p to POSIX path of (choose folder with prompt \\\"%s\\\")' -e 'return _p' 2>/dev/null\",\n"
"           prompt ? prompt->data : \"\");\n"
"  return stdr_capture_shell_first_line(cmd);\n"
"#elif defined(__linux__)\n"
"  char cmd[8192];\n"
"  snprintf(cmd, sizeof(cmd),\n"
"           \"zenity --file-selection --directory --title=\\\"%s\\\" 2>/dev/null\",\n"
"           prompt ? prompt->data : \"Open Folder\");\n"
"  return stdr_capture_shell_first_line(cmd);\n"
"#else\n"
"  (void)prompt;\n"
"  return YV_NULLV;\n"
"#endif\n"
"}\n"
"\n"
"static YisVal stdr_save_file_dialog(YisVal promptv, YisVal default_namev, YisVal extv) {\n"
"  if (promptv.tag != EVT_STR) yis_trap(\"save_file_dialog expects prompt string\");\n"
"  if (default_namev.tag != EVT_STR) yis_trap(\"save_file_dialog expects default_name string\");\n"
"  if (extv.tag != EVT_STR) yis_trap(\"save_file_dialog expects extension string\");\n"
"  YisStr* prompt = (YisStr*)promptv.as.p;\n"
"  YisStr* def = (YisStr*)default_namev.as.p;\n"
"  YisStr* ext = (YisStr*)extv.as.p;\n"
"#if defined(__APPLE__)\n"
"  char cmd[8192];\n"
"  snprintf(cmd, sizeof(cmd),\n"
"           \"osascript -e 'set _p to POSIX path of (choose file name with prompt \\\"%s\\\" default name \\\"%s\\\")' -e 'return _p' 2>/dev/null\",\n"
"           prompt ? prompt->data : \"\", def ? def->data : \"\");\n"
"  YisVal out = stdr_capture_shell_first_line(cmd);\n"
"  (void)ext;\n"
"  return out;\n"
"#elif defined(__linux__)\n"
"  char cmd[8192];\n"
"  snprintf(cmd, sizeof(cmd),\n"
"           \"zenity --file-selection --save --confirm-overwrite --title=\\\"%s\\\" --filename=\\\"%s\\\" 2>/dev/null\",\n"
"           prompt ? prompt->data : \"Save\", def ? def->data : \"\");\n"
"  (void)ext;\n"
"  return stdr_capture_shell_first_line(cmd);\n"
"#else\n"
"  (void)prompt;\n"
"  (void)def;\n"
"  (void)ext;\n"
"  return YV_NULLV;\n"
"#endif\n"
"}\n"
"\n"
"static size_t stdr_find_sub(const char* s, size_t slen, const char* sub, size_t sublen, size_t start) {\n"
"  if (sublen == 0) return start;\n"
"  if (start > slen) return (size_t)-1;\n"
"  for (size_t i = start; i + sublen <= slen; i++) {\n"
"    if (memcmp(s + i, sub, sublen) == 0) return i;\n"
"  }\n"
"  return (size_t)-1;\n"
"}\n"
"\n"
"static void stdr_trim_span(const char* s, size_t len, size_t* out_start, size_t* out_len) {\n"
"  size_t a = 0;\n"
"  while (a < len && (s[a] == ' ' || s[a] == '\\t')) a++;\n"
"  size_t b = len;\n"
"  while (b > a && (s[b - 1] == ' ' || s[b - 1] == '\\t')) b--;\n"
"  *out_start = a;\n"
"  *out_len = b - a;\n"
"}\n"
"\n"
"static YisStr* stdr_str_from_slice(const char* s, size_t len) {\n"
"  YisStr* st = (YisStr*)malloc(sizeof(YisStr) + len + 1);\n"
"  if (!st) yis_trap(\"out of memory\");\n"
"  st->ref = 1;\n"
"  st->len = len;\n"
"  st->data = (char*)(st + 1);\n"
"  if (len > 0) memcpy(st->data, s, len);\n"
"  st->data[len] = 0;\n"
"  return st;\n"
"}\n"
"\n"
"static YisVal stdr_args(void) {\n"
"  YisArr* a = stdr_arr_new(yis_argc > 0 ? yis_argc : 1);\n"
"  for (int i = 0; i < yis_argc; i++) {\n"
"    const char* s = yis_argv && yis_argv[i] ? yis_argv[i] : \"\";\n"
"    size_t len = strlen(s);\n"
"    yis_arr_add(a, YV_STR(stdr_str_from_slice(s, len)));\n"
"  }\n"
"  return YV_ARR(a);\n"
"}\n"
"\n"
"static int64_t stdr_parse_int_slice(const char* s, size_t len) {\n"
"  if (len == 0) return 0;\n"
"  char stack[64];\n"
"  char* tmp = (len < sizeof(stack)) ? stack : (char*)malloc(len + 1);\n"
"  if (!tmp) yis_trap(\"out of memory\");\n"
"  memcpy(tmp, s, len);\n"
"  tmp[len] = 0;\n"
"  char* end = NULL;\n"
"  long long v = strtoll(tmp, &end, 10);\n"
"  if (tmp != stack) free(tmp);\n"
"  if (end == tmp) return 0;\n"
"  return (int64_t)v;\n"
"}\n"
"\n"
"static double stdr_parse_float_slice(const char* s, size_t len) {\n"
"  if (len == 0) return 0.0;\n"
"  char stack[64];\n"
"  char* tmp = (len < sizeof(stack)) ? stack : (char*)malloc(len + 1);\n"
"  if (!tmp) yis_trap(\"out of memory\");\n"
"  memcpy(tmp, s, len);\n"
"  tmp[len] = 0;\n"
"  char* end = NULL;\n"
"  double v = strtod(tmp, &end);\n"
"  if (tmp != stack) free(tmp);\n"
"  if (end == tmp) return 0.0;\n"
"  return v;\n"
"}\n"
"\n"
"static bool stdr_parse_bool_slice(const char* s, size_t len) {\n"
"  if (len == 1) {\n"
"    if (s[0] == '1') return true;\n"
"    if (s[0] == '0') return false;\n"
"  }\n"
"  if (len == 4) {\n"
"    return ((s[0] == 't' || s[0] == 'T') &&\n"
"            (s[1] == 'r' || s[1] == 'R') &&\n"
"            (s[2] == 'u' || s[2] == 'U') &&\n"
"            (s[3] == 'e' || s[3] == 'E'));\n"
"  }\n"
"  return false;\n"
"}\n"
"\n"
"static YisVal stdr_readf_parse(YisVal fmt, YisVal line, YisVal args) {\n"
"  if (fmt.tag != EVT_STR) yis_trap(\"readf expects string format\");\n"
"  if (line.tag != EVT_STR) yis_trap(\"readf expects string input\");\n"
"  if (args.tag != EVT_ARR) yis_trap(\"readf expects args tuple\");\n"
"\n"
"  YisStr* fs = (YisStr*)fmt.as.p;\n"
"  YisStr* ls = (YisStr*)line.as.p;\n"
"  YisArr* a = (YisArr*)args.as.p;\n"
"\n"
"  const char* f = fs->data;\n"
"  size_t flen = fs->len;\n"
"  const char* s = ls->data;\n"
"  size_t slen = ls->len;\n"
"\n"
"  int segs = 1;\n"
"  for (size_t i = 0; i + 1 < flen; i++) {\n"
"    if (f[i] == '{' && f[i + 1] == '}') {\n"
"      segs++;\n"
"      i++;\n"
"    }\n"
"  }\n"
"\n"
"  const char* stack_ptrs[16];\n"
"  size_t stack_lens[16];\n"
"  const char** seg_ptrs = (segs <= 16) ? stack_ptrs : (const char**)malloc(sizeof(char*) * segs);\n"
"  size_t* seg_lens = (segs <= 16) ? stack_lens : (size_t*)malloc(sizeof(size_t) * segs);\n"
"  if (!seg_ptrs || !seg_lens) yis_trap(\"out of memory\");\n"
"\n"
"  size_t seg_start = 0;\n"
"  int seg_idx = 0;\n"
"  for (size_t i = 0; i + 1 < flen; i++) {\n"
"    if (f[i] == '{' && f[i + 1] == '}') {\n"
"      seg_ptrs[seg_idx] = f + seg_start;\n"
"      seg_lens[seg_idx] = i - seg_start;\n"
"      seg_idx++;\n"
"      i++;\n"
"      seg_start = i + 1;\n"
"    }\n"
"  }\n"
"  seg_ptrs[seg_idx] = f + seg_start;\n"
"  seg_lens[seg_idx] = flen - seg_start;\n"
"\n"
"  int placeholders = segs - 1;\n"
"\n"
"  size_t spos = 0;\n"
"  if (seg_lens[0] > 0) {\n"
"    size_t found = stdr_find_sub(s, slen, seg_ptrs[0], seg_lens[0], 0);\n"
"    if (found != (size_t)-1) spos = found + seg_lens[0];\n"
"  }\n"
"\n"
"  YisArr* out = stdr_arr_new((int)a->len);\n"
"\n"
"  for (size_t i = 0; i < a->len; i++) {\n"
"    size_t cap_start = spos;\n"
"    size_t cap_len = 0;\n"
"    if ((int)i < placeholders) {\n"
"      size_t found = stdr_find_sub(s, slen, seg_ptrs[i + 1], seg_lens[i + 1], spos);\n"
"      if (found == (size_t)-1) {\n"
"        cap_len = slen - spos;\n"
"        spos = slen;\n"
"      } else {\n"
"        cap_len = found - spos;\n"
"        spos = found + seg_lens[i + 1];\n"
"      }\n"
"    }\n"
"\n"
"    size_t trim_start = 0;\n"
"    size_t trim_len = cap_len;\n"
"    stdr_trim_span(s + cap_start, cap_len, &trim_start, &trim_len);\n"
"    const char* cap = (cap_len > 0) ? (s + cap_start + trim_start) : \"\";\n"
"\n"
"    YisVal hint = a->items[i];\n"
"    YisVal v;\n"
"    if (hint.tag == EVT_INT) {\n"
"      v = YV_INT(stdr_parse_int_slice(cap, trim_len));\n"
"    } else if (hint.tag == EVT_FLOAT) {\n"
"      v = YV_FLOAT(stdr_parse_float_slice(cap, trim_len));\n"
"    } else if (hint.tag == EVT_BOOL) {\n"
"      v = YV_BOOL(stdr_parse_bool_slice(cap, trim_len));\n"
"    } else if (hint.tag == EVT_STR) {\n"
"      v = YV_STR(stdr_str_from_slice(cap, trim_len));\n"
"    } else {\n"
"      v = YV_STR(stdr_str_from_slice(cap, trim_len));\n"
"    }\n"
"    yis_arr_add(out, v);\n"
"  }\n"
"\n"
"  if (seg_ptrs != stack_ptrs) free(seg_ptrs);\n"
"  if (seg_lens != stack_lens) free(seg_lens);\n"
"\n"
"  return YV_ARR(out);\n"
"}\n"
"\n"
"static YisStr* stdr_to_string(YisVal v) {\n"
"  char buf[64];\n"
"  if (v.tag == EVT_NULL) return &yis_static_null;\n"
"  if (v.tag == EVT_BOOL) return v.as.b ? &yis_static_true : &yis_static_false;\n"
"  if (v.tag == EVT_INT) {\n"
"    snprintf(buf, sizeof(buf), \"%lld\", (long long)v.as.i);\n"
"    return stdr_str_lit(buf);\n"
"  }\n"
"  if (v.tag == EVT_FLOAT) {\n"
"    snprintf(buf, sizeof(buf), \"%.6f\", v.as.f);\n"
"    return stdr_str_lit(buf);\n"
"  }\n"
"  if (v.tag == EVT_STR) {\n"
"    yis_retain_val(v);\n"
"    return (YisStr*)v.as.p;\n"
"  }\n"
"  if (v.tag == EVT_ARR) return &yis_static_array;\n"
"  if (v.tag == EVT_DICT) return &yis_static_dict;\n"
"  if (v.tag == EVT_OBJ) return &yis_static_object;\n"
"  if (v.tag == EVT_FN) return &yis_static_function;\n"
"  return &yis_static_unknown;\n"
"}\n"
"\n"
"static YisStr* stdr_str_from_parts(int n, YisVal* parts) {\n"
"  size_t total = 0;\n"
"  YisStr* stack_strs[16];\n"
"  YisStr** strs = (n <= 16) ? stack_strs : (YisStr**)malloc(sizeof(YisStr*) * (size_t)n);\n"
"  for (int i = 0; i < n; i++) {\n"
"    strs[i] = stdr_to_string(parts[i]);\n"
"    total += strs[i]->len;\n"
"  }\n"
"  YisStr* out = (YisStr*)malloc(sizeof(YisStr) + total + 1);\n"
"  out->ref = 1;\n"
"  out->len = total;\n"
"  out->data = (char*)(out + 1);\n"
"  size_t off = 0;\n"
"  for (int i = 0; i < n; i++) {\n"
"    memcpy(out->data + off, strs[i]->data, strs[i]->len);\n"
"    off += strs[i]->len;\n"
"    yis_release_val(YV_STR(strs[i]));\n"
"  }\n"
"  out->data[total] = 0;\n"
"  if (strs != stack_strs) free(strs);\n"
"  return out;\n"
"}\n"
"\n"
"static void yis_retain_val(YisVal v) {\n"
"  if (v.tag == EVT_STR) { int* r = &((YisStr*)v.as.p)->ref; if (*r != INT32_MAX) (*r)++; }\n"
"  else if (v.tag == EVT_ARR) ((YisArr*)v.as.p)->ref++;\n"
"  else if (v.tag == EVT_DICT) ((YisDict*)v.as.p)->ref++;\n"
"  else if (v.tag == EVT_OBJ) ((YisObj*)v.as.p)->ref++;\n"
"  else if (v.tag == EVT_FN) ((YisFn*)v.as.p)->ref++;\n"
"}\n"
"\n"
"static void yis_release_val(YisVal v) {\n"
"  if (v.tag == EVT_STR) {\n"
"    YisStr* s = (YisStr*)v.as.p;\n"
"    if (s->ref == INT32_MAX) return;\n"
"    if (--s->ref == 0) {\n"
"      if (s->data != (char*)(s + 1)) free(s->data);\n"
"      free(s);\n"
"    }\n"
"  } else if (v.tag == EVT_ARR) {\n"
"    YisArr* a = (YisArr*)v.as.p;\n"
"    if (--a->ref == 0) {\n"
"      for (size_t i = 0; i < a->len; i++) yis_release_val(a->items[i]);\n"
"      free(a->items);\n"
"      free(a);\n"
"    }\n"
"  } else if (v.tag == EVT_DICT) {\n"
"    YisDict* d = (YisDict*)v.as.p;\n"
"    if (--d->ref == 0) {\n"
"      for (size_t i = 0; i < d->len; i++) {\n"
"        yis_release_val(YV_STR(d->entries[i].key));\n"
"        yis_release_val(d->entries[i].val);\n"
"      }\n"
"      free(d->entries);\n"
"      free(d);\n"
"    }\n"
"  } else if (v.tag == EVT_OBJ) {\n"
"    YisObj* o = (YisObj*)v.as.p;\n"
"    if (--o->ref == 0) {\n"
"      if (o->drop) o->drop(o);\n"
"      free(o);\n"
"    }\n"
"  } else if (v.tag == EVT_FN) {\n"
"    YisFn* f = (YisFn*)v.as.p;\n"
"    if (--f->ref == 0) {\n"
"      if (f->env && f->env_size > 0) {\n"
"        YisRef** caps = (YisRef**)f->env;\n"
"        for (int i = 0; i < f->env_size; i++) yis_ref_release(caps[i]);\n"
"        free(f->env);\n"
"      }\n"
"      free(f);\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"static YisVal yis_move(YisVal* slot) {\n"
"  YisVal v = *slot;\n"
"  *slot = YV_NULLV;\n"
"  return v;\n"
"}\n"
"\n"
"static void yis_move_into(YisVal* slot, YisVal v) {\n"
"  yis_retain_val(v);\n"
"  yis_release_val(*slot);\n"
"  *slot = v;\n"
"}\n"
"\n"
"static int64_t yis_as_int(YisVal v) {\n"
"  if (v.tag == EVT_INT) return v.as.i;\n"
"  if (v.tag == EVT_BOOL) return v.as.b ? 1 : 0;\n"
"  if (v.tag == EVT_FLOAT) return (int64_t)v.as.f;\n"
"  if (v.tag == EVT_NULL) return 0;\n"
"  if (v.tag == EVT_STR) {\n"
"    /* Coerce string to int when possible; otherwise 0 (avoids trap until codegen is fully audited) */\n"
"    YisStr *s = (YisStr*)v.as.p;\n"
"    if (s && s->len > 0 && s->len < 32) {\n"
"      char buf[32];\n"
"      memcpy(buf, s->data, s->len);\n"
"      buf[s->len] = '\\0';\n"
"      char *end = NULL;\n"
"      long x = strtol(buf, &end, 10);\n"
"      if (end && end == buf + (ptrdiff_t)s->len)\n"
"        return (int64_t)x;\n"
"    }\n"
"    return 0;\n"
"  }\n"
"  {\n"
"    const char *tag_name = \"?\";\n"
"    switch (v.tag) {\n"
"      case EVT_NULL: tag_name = \"null\"; break;\n"
"      case EVT_STR: tag_name = \"string\"; break;\n"
"      case EVT_ARR: tag_name = \"array\"; break;\n"
"      case EVT_DICT: tag_name = \"dict\"; break;\n"
"      case EVT_OBJ: tag_name = \"object\"; break;\n"
"      case EVT_FN: tag_name = \"function\"; break;\n"
"      default: tag_name = \"unknown\"; break;\n"
"    }\n"
"    char buf[80];\n"
"    snprintf(buf, sizeof(buf), \"type mismatch: expected int (got %s)\", tag_name);\n"
"    yis_trap(buf);\n"
"  }\n"
"  return 0;\n"
"}\n"
"\n"
"static double yis_as_float(YisVal v) {\n"
"  if (v.tag == EVT_FLOAT) return v.as.f;\n"
"  if (v.tag == EVT_INT) return (double)v.as.i;\n"
"  if (v.tag == EVT_NULL) return 0.0;\n"
"  if (v.tag == EVT_BOOL) return v.as.b ? 1.0 : 0.0;\n"
"  if (v.tag == EVT_STR) {\n"
"    YisStr *s = (YisStr*)v.as.p;\n"
"    if (s && s->len > 0 && s->len < 32) {\n"
"      char buf[32];\n"
"      memcpy(buf, s->data, s->len);\n"
"      buf[s->len] = '\\0';\n"
"      char *end = NULL;\n"
"      double x = strtod(buf, &end);\n"
"      if (end && end == buf + (ptrdiff_t)s->len)\n"
"        return x;\n"
"    }\n"
"    return 0.0;\n"
"  }\n"
"  {\n"
"    const char *tag_name = \"?\";\n"
"    switch (v.tag) {\n"
"      case EVT_NULL: tag_name = \"null\"; break;\n"
"      case EVT_ARR: tag_name = \"array\"; break;\n"
"      case EVT_DICT: tag_name = \"dict\"; break;\n"
"      case EVT_OBJ: tag_name = \"object\"; break;\n"
"      case EVT_FN: tag_name = \"function\"; break;\n"
"      default: tag_name = \"unknown\"; break;\n"
"    }\n"
"    char buf[80];\n"
"    snprintf(buf, sizeof(buf), \"type mismatch: expected float (got %s)\", tag_name);\n"
"    yis_trap(buf);\n"
"  }\n"
"  return 0.0;\n"
"}\n"
"\n"
"static bool yis_as_bool(YisVal v) {\n"
"  if (v.tag == EVT_BOOL) return v.as.b;\n"
"  if (v.tag == EVT_NULL) return false;\n"
"  if (v.tag == EVT_INT) return v.as.i != 0;\n"
"  if (v.tag == EVT_FLOAT) return v.as.f != 0.0;\n"
"  if (v.tag == EVT_STR) return ((YisStr*)v.as.p)->len != 0;\n"
"  if (v.tag == EVT_ARR) return ((YisArr*)v.as.p)->len != 0;\n"
"  if (v.tag == EVT_DICT) return ((YisDict*)v.as.p)->len != 0;\n"
"  return true;\n"
"}\n"
"\n"
"static YisVal yis_add(YisVal a, YisVal b) {\n"
"  if (a.tag == EVT_STR || b.tag == EVT_STR) return stdr_str_concat(a, b);\n"
"  if (a.tag == EVT_FLOAT || b.tag == EVT_FLOAT) return YV_FLOAT(yis_as_float(a) + yis_as_float(b));\n"
"  return YV_INT(yis_as_int(a) + yis_as_int(b));\n"
"}\n"
"\n"
"static YisVal yis_sub(YisVal a, YisVal b) {\n"
"  if (a.tag == EVT_FLOAT || b.tag == EVT_FLOAT) return YV_FLOAT(yis_as_float(a) - yis_as_float(b));\n"
"  return YV_INT(yis_as_int(a) - yis_as_int(b));\n"
"}\n"
"\n"
"static YisVal yis_mul(YisVal a, YisVal b) {\n"
"  if (a.tag == EVT_FLOAT || b.tag == EVT_FLOAT) return YV_FLOAT(yis_as_float(a) * yis_as_float(b));\n"
"  return YV_INT(yis_as_int(a) * yis_as_int(b));\n"
"}\n"
"\n"
"static YisVal yis_div(YisVal a, YisVal b) {\n"
"  if (a.tag == EVT_FLOAT || b.tag == EVT_FLOAT) return YV_FLOAT(yis_as_float(a) / yis_as_float(b));\n"
"  return YV_INT(yis_as_int(a) / yis_as_int(b));\n"
"}\n"
"\n"
"static YisVal yis_mod(YisVal a, YisVal b) {\n"
"  if (a.tag == EVT_FLOAT || b.tag == EVT_FLOAT) yis_trap(\"% expects integer\");\n"
"  return YV_INT(yis_as_int(a) % yis_as_int(b));\n"
"}\n"
"\n"
"static YisVal yis_neg(YisVal a) {\n"
"  if (a.tag == EVT_FLOAT) return YV_FLOAT(-a.as.f);\n"
"  return YV_INT(-yis_as_int(a));\n"
"}\n"
"\n"
"static YisVal yis_eq(YisVal a, YisVal b) {\n"
"  if (a.tag != b.tag) return YV_BOOL(false);\n"
"  switch (a.tag) {\n"
"    case EVT_NULL: return YV_BOOL(true);\n"
"    case EVT_BOOL: return YV_BOOL(a.as.b == b.as.b);\n"
"    case EVT_INT: return YV_BOOL(a.as.i == b.as.i);\n"
"    case EVT_FLOAT: return YV_BOOL(a.as.f == b.as.f);\n"
"    case EVT_STR: {\n"
"      YisStr* sa = (YisStr*)a.as.p;\n"
"      YisStr* sb = (YisStr*)b.as.p;\n"
"      if (sa->len != sb->len) return YV_BOOL(false);\n"
"      return YV_BOOL(memcmp(sa->data, sb->data, sa->len) == 0);\n"
"    }\n"
"    default: return YV_BOOL(a.as.p == b.as.p);\n"
"  }\n"
"}\n"
"\n"
"static YisVal yis_ne(YisVal a, YisVal b) {\n"
"  YisVal v = yis_eq(a, b);\n"
"  return YV_BOOL(!v.as.b);\n"
"}\n"
"\n"
"static YisVal yis_lt(YisVal a, YisVal b) { return YV_BOOL(yis_as_float(a) < yis_as_float(b)); }\n"
"static YisVal yis_le(YisVal a, YisVal b) { return YV_BOOL(yis_as_float(a) <= yis_as_float(b)); }\n"
"static YisVal yis_gt(YisVal a, YisVal b) { return YV_BOOL(yis_as_float(a) > yis_as_float(b)); }\n"
"static YisVal yis_ge(YisVal a, YisVal b) { return YV_BOOL(yis_as_float(a) >= yis_as_float(b)); }\n"
"\n"
"static YisArr* stdr_arr_new(int n) {\n"
"  YisArr* a = (YisArr*)malloc(sizeof(YisArr));\n"
"  a->ref = 1;\n"
"  a->len = 0;\n"
"  a->cap = (n > 0) ? (size_t)n : 4;\n"
"  a->items = (YisVal*)malloc(sizeof(YisVal) * a->cap);\n"
"  return a;\n"
"}\n"
"\n"
"static void yis_arr_add(YisArr* a, YisVal v) {\n"
"  if (a->len >= a->cap) {\n"
"    a->cap *= 2;\n"
"    a->items = (YisVal*)realloc(a->items, sizeof(YisVal) * a->cap);\n"
"  }\n"
"  a->items[a->len++] = v;\n"
"}\n"
"\n"
"static void stdr_push(YisVal av, YisVal val) {\n"
"  if (av.tag != EVT_ARR) yis_trap(\"push expects array\");\n"
"  YisArr* a = (YisArr*)av.as.p;\n"
"  yis_retain_val(val);\n"
"  yis_arr_add(a, val);\n"
"}\n"
"\n"
"static YisVal stdr_join(YisVal av) {\n"
"  if (av.tag != EVT_ARR) yis_trap(\"join expects array\");\n"
"  YisArr* a = (YisArr*)av.as.p;\n"
"  return YV_STR(stdr_str_from_parts((int)a->len, a->items));\n"
"}\n"
"\n"
"static YisVal stdr_array_concat(YisVal av, YisVal bv) {\n"
"  if (av.tag != EVT_ARR || bv.tag != EVT_ARR) yis_trap(\"concat expects two arrays\");\n"
"  YisArr* a = (YisArr*)av.as.p;\n"
"  YisArr* b = (YisArr*)bv.as.p;\n"
"  YisArr* out = stdr_arr_new((int)(a->len + b->len));\n"
"  for (size_t i = 0; i < a->len; i++) {\n"
"    yis_retain_val(a->items[i]);\n"
"    yis_arr_add(out, a->items[i]);\n"
"  }\n"
"  for (size_t i = 0; i < b->len; i++) {\n"
"    yis_retain_val(b->items[i]);\n"
"    yis_arr_add(out, b->items[i]);\n"
"  }\n"
"  return YV_ARR(out);\n"
"}\n"
"\n"
"static YisVal yis_arr_get(YisArr* a, int64_t idx) {\n"
"  if (!a) yis_trap(\"array index on null\");\n"
"  if (idx < 0 || (size_t)idx >= a->len) return YV_NULLV;\n"
"  YisVal v = a->items[idx];\n"
"  yis_retain_val(v);\n"
"  return v;\n"
"}\n"
"\n"
"static void yis_arr_set(YisArr* a, int64_t idx, YisVal v) {\n"
"  if (idx < 0) return;\n"
"  size_t uidx = (size_t)idx;\n"
"  if (uidx >= a->len) {\n"
"    if (uidx >= a->cap) {\n"
"      size_t new_cap = a->cap ? a->cap : 4;\n"
"      while (new_cap <= uidx) new_cap *= 2;\n"
"      a->items = (YisVal*)realloc(a->items, sizeof(YisVal) * new_cap);\n"
"      a->cap = new_cap;\n"
"    }\n"
"    for (size_t i = a->len; i <= uidx; i++) a->items[i] = YV_NULLV;\n"
"    a->len = uidx + 1;\n"
"  } else {\n"
"    yis_release_val(a->items[uidx]);\n"
"  }\n"
"  yis_retain_val(v);\n"
"  a->items[uidx] = v;\n"
"}\n"
"\n"
"static YisVal yis_arr_remove(YisArr* a, int64_t idx) {\n"
"  if (idx < 0 || (size_t)idx >= a->len) return YV_NULLV;\n"
"  YisVal v = a->items[idx];\n"
"  for (size_t i = (size_t)idx; i + 1 < a->len; i++) {\n"
"    a->items[i] = a->items[i + 1];\n"
"  }\n"
"  a->len--;\n"
"  return v;\n"
"}\n"
"\n"
"static int yis_str_cmp(YisStr* a, YisStr* b) {\n"
"  if (a->len != b->len) return (a->len > b->len) ? 1 : -1;\n"
"  return memcmp(a->data, b->data, a->len);\n"
"}\n"
"\n"
"static YisDict* stdr_dict_new(void) {\n"
"  YisDict* d = (YisDict*)malloc(sizeof(YisDict));\n"
"  d->ref = 1;\n"
"  d->len = 0;\n"
"  d->cap = 8;\n"
"  d->entries = (YisDictEnt*)malloc(sizeof(YisDictEnt) * d->cap);\n"
"  return d;\n"
"}\n"
"\n"
"static void yis_dict_set(YisDict* d, YisVal key, YisVal val) {\n"
"  if (key.tag != EVT_STR) yis_trap(\"dict key must be string\");\n"
"  YisStr* k = (YisStr*)key.as.p;\n"
"  for (size_t i = 0; i < d->len; i++) {\n"
"    if (yis_str_cmp(d->entries[i].key, k) == 0) {\n"
"      yis_retain_val(val);\n"
"      yis_release_val(d->entries[i].val);\n"
"      d->entries[i].val = val;\n"
"      return;\n"
"    }\n"
"  }\n"
"  if (d->len >= d->cap) {\n"
"    d->cap *= 2;\n"
"    d->entries = (YisDictEnt*)realloc(d->entries, sizeof(YisDictEnt) * d->cap);\n"
"  }\n"
"  yis_retain_val(key);\n"
"  yis_retain_val(val);\n"
"  d->entries[d->len].key = k;\n"
"  d->entries[d->len].val = val;\n"
"  d->len++;\n"
"}\n"
"\n"
"static YisVal yis_dict_get(YisDict* d, YisVal key) {\n"
"  if (!d) return YV_NULLV;\n"
"  if ((uintptr_t)d < 4096u) return YV_NULLV;\n"
"  if (key.tag != EVT_STR) return YV_NULLV;\n"
"  YisStr* k = (YisStr*)key.as.p;\n"
"  if (!k) return YV_NULLV;\n"
"  if ((uintptr_t)k < 4096u) return YV_NULLV;\n"
"  for (size_t i = 0; i < d->len; i++) {\n"
"    if (yis_str_cmp(d->entries[i].key, k) == 0) {\n"
"      YisVal v = d->entries[i].val;\n"
"      yis_retain_val(v);\n"
"      return v;\n"
"    }\n"
"  }\n"
"  return YV_NULLV;\n"
"}\n"
"\n"
"static int yis_dict_len(YisDict* d) {\n"
"  return (int)d->len;\n"
"}\n"
"\n"
"static YisObj* yis_obj_new(size_t size, void (*drop)(YisObj*)) {\n"
"  YisObj* o = (YisObj*)malloc(size);\n"
"  o->ref = 1;\n"
"  o->drop = drop;\n"
"  return o;\n"
"}\n"
"\n"
"static YisRef* yis_ref_new(void) {\n"
"  YisRef* r = (YisRef*)malloc(sizeof(YisRef));\n"
"  if (!r) yis_trap(\"out of memory\");\n"
"  r->ref = 1;\n"
"  r->val = YV_NULLV;\n"
"  return r;\n"
"}\n"
"\n"
"static void yis_ref_retain(YisRef* r) {\n"
"  if (r) r->ref++;\n"
"}\n"
"\n"
"static void yis_ref_release(YisRef* r) {\n"
"  if (!r) return;\n"
"  if (--r->ref == 0) {\n"
"    yis_release_val(r->val);\n"
"    free(r);\n"
"  }\n"
"}\n"
"\n"
"static YisFn* yi_fn_new(YisVal (*fn)(void* env, int argc, YisVal* argv), int arity) {\n"
"  YisFn* f = (YisFn*)malloc(sizeof(YisFn));\n"
"  f->ref = 1;\n"
"  f->arity = arity;\n"
"  f->fn = fn;\n"
"  f->env = NULL;\n"
"  f->env_size = 0;\n"
"  return f;\n"
"}\n"
"\n"
"static YisFn* yi_fn_new_with_env(YisVal (*fn)(void* env, int argc, YisVal* argv), int arity, void* env, int env_size) {\n"
"  YisFn* f = (YisFn*)malloc(sizeof(YisFn));\n"
"  f->ref = 1;\n"
"  f->arity = arity;\n"
"  f->fn = fn;\n"
"  f->env = env;\n"
"  f->env_size = env_size;\n"
"  return f;\n"
"}\n"
"\n"
"static YisVal yis_call(YisVal fval, int argc, YisVal* argv) {\n"
"  if (fval.tag != EVT_FN) yis_trap(\"call expects function\");\n"
"  YisFn* f = (YisFn*)fval.as.p;\n"
"  if (f->arity >= 0 && f->arity != argc) yis_trap(\"arity mismatch\");\n"
"  return f->fn(f->env, argc, argv);\n"
"}\n"
"\n"
"static YisVal stdr_parse_hex(YisVal sv) {\n"
"  if (sv.tag != EVT_STR) yis_trap(\"parse_hex expects string\");\n"
"  YisStr* s = (YisStr*)sv.as.p;\n"
"  if (s->len == 0) return YV_INT(0);\n"
"  char* end = NULL;\n"
"  long long v = strtoll(s->data, &end, 16);\n"
"  if (end == s->data) return YV_INT(0);\n"
"  return YV_INT((int64_t)v);\n"
"}\n"
"\n"
"static YisVal stdr_char_from_code(YisVal cv) {\n"
"  int64_t code = yis_as_int(cv);\n"
"  if (code < 0 || code > 0x10FFFF) return YV_STR(&yis_static_empty);\n"
"  char buf[4];\n"
"  int len = 0;\n"
"  if (code <= 0x7F) {\n"
"    buf[0] = (char)code; len = 1;\n"
"  } else if (code <= 0x7FF) {\n"
"    buf[0] = (char)(0xC0 | ((code >> 6) & 0x1F));\n"
"    buf[1] = (char)(0x80 | (code & 0x3F));\n"
"    len = 2;\n"
"  } else if (code <= 0xFFFF) {\n"
"    buf[0] = (char)(0xE0 | ((code >> 12) & 0x0F));\n"
"    buf[1] = (char)(0x80 | ((code >> 6) & 0x3F));\n"
"    buf[2] = (char)(0x80 | (code & 0x3F));\n"
"    len = 3;\n"
"  } else {\n"
"    buf[0] = (char)(0xF0 | ((code >> 18) & 0x07));\n"
"    buf[1] = (char)(0x80 | ((code >> 12) & 0x3F));\n"
"    buf[2] = (char)(0x80 | ((code >> 6) & 0x3F));\n"
"    buf[3] = (char)(0x80 | (code & 0x3F));\n"
"    len = 4;\n"
"  }\n"
"  return YV_STR(stdr_str_from_slice(buf, (size_t)len));\n"
"}\n"
"\n"
"static YisVal stdr_floor(YisVal v) {\n"
"  double x = (v.tag == EVT_FLOAT) ? v.as.f : (double)yis_as_int(v);\n"
"  return YV_INT((int64_t)floor(x));\n"
"}\n"
"\n"
"static YisVal stdr_ceil(YisVal v) {\n"
"  double x = (v.tag == EVT_FLOAT) ? v.as.f : (double)yis_as_int(v);\n"
"  return YV_INT((int64_t)ceil(x));\n"
"}\n"
"\n"
"static YisVal stdr_keys(YisVal dv) {\n"
"  if (dv.tag != EVT_DICT) yis_trap(\"keys expects dict\");\n"
"  YisDict* d = (YisDict*)dv.as.p;\n"
"  YisArr* out = stdr_arr_new((int)d->len);\n"
"  for (size_t i = 0; i < d->len; i++) {\n"
"    YisVal k = YV_STR(d->entries[i].key);\n"
"    yis_retain_val(k);\n"
"    yis_arr_add(out, k);\n"
"  }\n"
"  return YV_ARR(out);\n"
"}\n"
"\n"
"static YisVal stdr_replace(YisVal textv, YisVal fromv, YisVal tov) {\n"
"  if (textv.tag != EVT_STR) yis_trap(\"replace expects string\");\n"
"  if (fromv.tag != EVT_STR) yis_trap(\"replace expects string\");\n"
"  if (tov.tag != EVT_STR) yis_trap(\"replace expects string\");\n"
"  YisStr* text = (YisStr*)textv.as.p;\n"
"  YisStr* from = (YisStr*)fromv.as.p;\n"
"  YisStr* to = (YisStr*)tov.as.p;\n"
"  if (from->len == 0) { yis_retain_val(textv); return textv; }\n"
"  size_t cap = text->len + 64;\n"
"  char* buf = (char*)malloc(cap);\n"
"  if (!buf) yis_trap(\"out of memory\");\n"
"  size_t out_len = 0;\n"
"  size_t i = 0;\n"
"  while (i + from->len <= text->len) {\n"
"    if (memcmp(text->data + i, from->data, from->len) == 0) {\n"
"      size_t need = out_len + to->len;\n"
"      if (need >= cap) {\n"
"        while (need >= cap) cap *= 2;\n"
"        buf = (char*)realloc(buf, cap);\n"
"        if (!buf) yis_trap(\"out of memory\");\n"
"      }\n"
"      memcpy(buf + out_len, to->data, to->len);\n"
"      out_len += to->len;\n"
"      i += from->len;\n"
"    } else {\n"
"      if (out_len + 1 >= cap) {\n"
"        cap *= 2;\n"
"        buf = (char*)realloc(buf, cap);\n"
"        if (!buf) yis_trap(\"out of memory\");\n"
"      }\n"
"      buf[out_len++] = text->data[i++];\n"
"    }\n"
"  }\n"
"  size_t tail = text->len - i;\n"
"  if (tail > 0) {\n"
"    if (out_len + tail >= cap) {\n"
"      cap = out_len + tail + 1;\n"
"      buf = (char*)realloc(buf, cap);\n"
"      if (!buf) yis_trap(\"out of memory\");\n"
"    }\n"
"    memcpy(buf + out_len, text->data + i, tail);\n"
"    out_len += tail;\n"
"  }\n"
"  buf[out_len] = 0;\n"
"  YisStr* result = stdr_str_from_slice(buf, out_len);\n"
"  free(buf);\n"
"  return YV_STR(result);\n"
"}\n"
"\n"
"// ---- External module bindings ----\n"
"// Injected by codegen when the program imports an external module.\n"
;
static const unsigned int yis_runtime_embedded_len = (unsigned int)(sizeof(yis_runtime_embedded) - 1);

#endif
